"""empty message

Revision ID: 505922608551
Revises: 21ffdee6cfea
Create Date: 2015-08-26 14:21:43.183651

"""

# revision identifiers, used by Alembic.
revision = '505922608551'
down_revision = '21ffdee6cfea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    ### end Alembic commands ###
