"""empty message

Revision ID: 5c2132bc5be
Revises: 505922608551
Create Date: 2015-10-07 14:50:38.853388

"""

# revision identifiers, used by Alembic.
revision = '5c2132bc5be'
down_revision = '505922608551'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('dissolved_oxygen', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('electro_conductivity', sa.Float(), nullable=True))
    op.add_column('measurements', sa.Column('temperature', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'temperature')
    op.drop_column('measurements', 'electro_conductivity')
    op.drop_column('measurements', 'dissolved_oxygen')
    ### end Alembic commands ###
